/**
 * Seed the GridCell table from the existing grid_cells.json.
 *
 * Source: private/docs/grid/data/grid_cells.json — generated by
 * scripts/generate-grid-prototype.ts (5nm cells, haversine to nearest
 * ASOS station, tier assignment via Don Berchoff's 5nm rule).
 *
 * Usage:
 *   # Miami only (default, what Day 1 of the grid build needs):
 *   npx tsx scripts/seed-grid-cells.ts
 *
 *   # All markets:
 *   npx tsx scripts/seed-grid-cells.ts --all
 *
 *   # Dry run (no DB writes):
 *   npx tsx scripts/seed-grid-cells.ts --dry
 *
 *   # Specific market:
 *   npx tsx scripts/seed-grid-cells.ts --market phoenix
 */
import { prisma } from "@/lib/prisma";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

interface RawCell {
  cellId: string;
  marketId: string;
  row: number;
  col: number;
  minLat: number;
  maxLat: number;
  minLng: number;
  maxLng: number;
  centroidLat: number;
  centroidLng: number;
  nearestAsosId?: string | null;
  nearestAsosDistanceNm?: number | null;
  tier: "full" | "partial" | "none";
  centroidCredit: number;
  siteIds?: string[];
}

interface RawGrid {
  marketId: string;
  cityName: string;
  rows: number;
  cols: number;
  summary: Record<string, number>;
  cells: RawCell[];
}

interface RawFile {
  generated: string;
  grids: RawGrid[];
}

const GRID_VERSION = "v1.4-preview";

function parseArgs() {
  const args = process.argv.slice(2);
  const all = args.includes("--all");
  const dry = args.includes("--dry");
  const marketArgIdx = args.indexOf("--market");
  const market = marketArgIdx >= 0 ? args[marketArgIdx + 1] : null;
  return { all, dry, market };
}

async function main() {
  const { all, dry, market } = parseArgs();

  const filePath = resolve(process.cwd(), "private/docs/grid/data/grid_cells.json");
  const raw: RawFile = JSON.parse(readFileSync(filePath, "utf-8"));

  // Filter to the markets we want to seed
  let grids = raw.grids;
  if (market) {
    grids = grids.filter((g) => g.marketId === market);
  } else if (!all) {
    grids = grids.filter((g) => g.marketId === "miami");
  }

  if (grids.length === 0) {
    console.error(`No grids matched the filter. Available: ${raw.grids.map((g) => g.marketId).join(", ")}`);
    process.exit(1);
  }

  console.log(
    `\nSeeding GridCell from ${filePath}`,
  );
  console.log(`  Generator stamp: ${raw.generated}`);
  console.log(`  Version: ${GRID_VERSION}`);
  console.log(`  Markets: ${grids.map((g) => g.marketId).join(", ")}`);
  console.log(`  Total cells to seed: ${grids.reduce((n, g) => n + g.cells.length, 0)}`);
  console.log(`  Mode: ${dry ? "DRY RUN (no writes)" : "WRITE"}\n`);

  let seeded = 0;
  let skipped = 0;

  for (const grid of grids) {
    console.log(`\n[${grid.marketId}] ${grid.cityName} — ${grid.cells.length} cells`);
    console.log(
      `  tiers: full=${grid.summary.cellsFull ?? "?"}  partial=${grid.summary.cellsPartial ?? "?"}  none=${grid.summary.cellsNone ?? "?"}  avgCredit=${grid.summary.avgCoverageCredit ?? "?"}`,
    );

    if (!dry) {
      // Wipe existing rows for this market + version to keep reseed idempotent
      const deleted = await prisma.gridCell.deleteMany({
        where: { marketId: grid.marketId, gridVersion: GRID_VERSION },
      });
      if (deleted.count > 0) {
        console.log(`  cleared ${deleted.count} existing rows for reseed`);
      }

      // Bulk insert
      const rows = grid.cells.map((c) => ({
        id: c.cellId,
        marketId: c.marketId,
        row: c.row,
        col: c.col,
        minLat: c.minLat,
        maxLat: c.maxLat,
        minLng: c.minLng,
        maxLng: c.maxLng,
        centroidLat: c.centroidLat,
        centroidLng: c.centroidLng,
        nearestAsosId: c.nearestAsosId ?? null,
        nearestAsosDistanceNm: c.nearestAsosDistanceNm ?? null,
        tier: c.tier,
        centroidCredit: c.centroidCredit,
        siteIds: c.siteIds ?? [],
        gridVersion: GRID_VERSION,
      }));

      const created = await prisma.gridCell.createMany({
        data: rows,
        skipDuplicates: true,
      });
      seeded += created.count;
      skipped += rows.length - created.count;
      console.log(`  inserted: ${created.count}${rows.length - created.count > 0 ? `, skipped duplicates: ${rows.length - created.count}` : ""}`);
    }
  }

  console.log(`\n${dry ? "(dry run) " : ""}Total seeded: ${seeded}${skipped > 0 ? ` (${skipped} duplicates skipped)` : ""}`);

  // Verification
  if (!dry) {
    const counts = await prisma.gridCell.groupBy({
      by: ["marketId", "tier"],
      _count: true,
      where: { marketId: { in: grids.map((g) => g.marketId) } },
      orderBy: [{ marketId: "asc" }, { tier: "asc" }],
    });
    console.log(`\nDB verification:`);
    for (const c of counts) {
      console.log(`  ${c.marketId.padEnd(18)} ${c.tier.padEnd(8)} ${c._count}`);
    }
  }

  await prisma.$disconnect();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
